apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: harshalmali02/shopping-website-python  # ← replace with your correct Docker Hub image
          ports:
            - containerPort: 5000

