apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: harsh042/shopping-website-python
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
