apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: LoadBalancer
  selector:
    app: shopping
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP


